# Análisis EDA y Decisiones de Negocio en Ventas de Automóviles

Este notebook contiene 15 ejercicios que combinan análisis exploratorio de datos (EDA) y reflexiones críticas de negocio. Cada punto incluye instrucciones detalladas, paso a paso, para realizar agrupaciones y filtros, de modo que se guíe al estudiante en cada parte del proceso.

La estructura del dataset es la siguiente:

```
year, make, model, trim, body, transmission, vin, state, condition, odometer, color, interior, seller, mmr, sellingprice, saledate
```

¡Comienza el análisis y sigue cada paso para proponer estrategias de negocio basadas en los resultados!

In [1]:
# Descargar y descomprimir el dataset
!wget https://github.com/javierherrera1996/lecture_analytics/raw/main/cars_dataset.zip
!unzip -o cars_dataset.zip

--2025-03-13 20:27:50--  https://github.com/javierherrera1996/lecture_analytics/raw/main/cars_dataset.zip
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/javierherrera1996/lecture_analytics/main/cars_dataset.zip [following]
--2025-03-13 20:27:51--  https://raw.githubusercontent.com/javierherrera1996/lecture_analytics/main/cars_dataset.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19753181 (19M) [application/zip]
Saving to: ‘cars_dataset.zip’

cars_dataset.zip    100%[===================>]  18.84M  90.9MB/s    in 0.2s

2025-03-13 20:27:51 (90.9 MB/s) - ‘cars_dataset.zip’ saved [19753181/19753181]

Archive:  cars_dataset.zip
  inflating: car_prices.csv

## 1. Dimensiones y Representatividad del Dataset

a) Carga el dataset (desde un archivo CSV) y muestra sus dimensiones (número de filas y columnas).

b) Describe brevemente qué representa cada fila y reflexiona: ¿Crees que el dataset es representativo del mercado de ventas de automóviles? Justifica tu respuesta.

Rta: Cada fila del dataset representa la venta de un automóvil, registrando características como la marca, modelo, año, condición, kilometraje, precio de venta, entre otros.
La verdad creería que sí, ya que el dataset es representativo porque además tiene un buen número de registros.

In [2]:
import pandas as pd

data = pd.read_csv('car_prices.csv')

In [3]:
data.shape

(558837, 16)

## 2. Ventas Totales y Promedio

a) Calcula la suma total y el promedio de la columna `sellingprice`.

b) Caso de negocio: Si el precio promedio es bajo, ¿qué estrategias de precio o promociones sugerirías para aumentar la rentabilidad? Explica tu respuesta.

Rta: Si depronto se está buscando aumentar la rentabilidad, lo que propondría sería negociar únicamente con cierto tipo de marcas (como BMW, Audi, Toyota, Ford) o estas marcas consideradas "luxury", y mejorar el control de calidad, para que los clientes perciban que con nosotros solo van a tener buena calidad.

In [6]:
data['sellingprice'].mean()

13611.358810003132

In [8]:
data['sellingprice'].sum()

7606367587.0

## 3. Distribución de Ventas por Marca

a) Utiliza `value_counts()` para determinar cuántas ventas se registraron por cada marca (`make`).

b) Caso de negocio: ¿Qué marcas parecen dominar el mercado? Basado en esta distribución, ¿en qué marcas invertirías en publicidad y por qué?

Rta: Las principales marcas que salen son Ford, Chevrolet, Nissan, Toyota y Dodge; si lo tomamos de la mano con el punto anterior, invertiría en publicidad para Toyota y Ford ya que con estas aseguramos un buen número de ventas, y si pensamos sólo hacer negocios con marcas "luxury" sería el primer paso para empezar a darle una reputación a nuestra marca.

In [9]:
data['make'].value_counts()

make
Ford          93554
Chevrolet     60197
Nissan        53946
Toyota        39871
Dodge         30710
              ...
airstream         1
ford tk           1
chev truck        1
hyundai tk        1
Lotus             1
Name: count, Length: 96, dtype: int64

## 4. Segmentación de Clientes por Kilometraje

a) Crea un DataFrame filtrado que incluya únicamente las ventas donde el `odometer` es menor a 20,000 millas. Cuantos Vehiculos tiene este dataset?

b) Caso de negocio: Este segmento de vehículos con bajo uso puede tener mayor valor percibido. ¿Cómo ajustarías la estrategia de marketing para este grupo?

Rta: Para este punto sería bueno utilizar la publicidad, aprovechar que hemos generado un "status" y presentar estos vehículos como una opción premium, justificando un precio ligeramente superior a los de otros sitios y dirigirnos a un público que busque calidad y esté dispuesto a pagar más por ella; y también podríamos utilizar imágenes de alta calidad en la publicidad y en la presentación de los vehículos, y frases como "Excelente estado", "Buena calidad", ó "Casi nuevo".

In [11]:
data[data['odometer'] < 20000]

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558812,2012,Nissan,Maxima,3.5 SV,sedan,NaN,1n4aa5ap7cc840019,pa,42.0,9861.0,brown,tan,nissan-infiniti lt,18650.0,19700.0,Tue Jul 07 2015 07:30:00 GMT-0700 (PDT)
558826,2014,Jeep,Grand Cherokee,Limited,SUV,automatic,1c4rjebg4ec573100,ca,44.0,9024.0,gray,black,enterprise vehicle exchange / tra / rental / t...,29800.0,17300.0,Thu Jul 09 2015 09:00:00 GMT-0700 (PDT)
558832,2015,Kia,K900,Luxury,Sedan,NaN,knalw4d4xf6019304,in,45.0,18255.0,silver,black,avis corporation,35300.0,33000.0,Thu Jul 09 2015 07:00:00 GMT-0700 (PDT)
558835,2015,Nissan,Altima,2.5 S,sedan,automatic,1n4al3ap0fc216050,ga,38.0,16658.0,white,black,enterprise vehicle exchange / tra / rental / t...,15100.0,11100.0,Thu Jul 09 2015 06:45:00 GMT-0700 (PDT)
558836,2014,Ford,F-150,XLT,SuperCrew,automatic,1ftfw1et2eke87277,ca,34.0,15008.0,gray,gray,ford motor credit company llc pd,29600.0,26700.0,Thu May 28 2015 05:30:00 GMT-0700 (PDT)

In [12]:
df=data[data['odometer'] < 20000]

In [13]:
df.shape

(84206, 16)

## 5. Agrupación por Marca: Precio y Volumen

a) Agrupa el dataset por `make` y calcula:
   - El promedio de `sellingprice`.
   - La cantidad de ventas por marca (usa el conteo de registros como proxy).

b) Caso de negocio: Si una marca tiene alto volumen pero precios bajos, ¿qué medidas recomendarías para mejorar el margen?

Rta: Es básicamente relacionado con los puntos anteriores, sería centrar nuestra atención y publicidad en estas marcas (Ford, Toyota, BMW y Audi) que brindan sentimiento de lujo y calidad a los consumidores, y que además vienen acompañadas de altas ventas, sin descuidar las otras como Ferrari o Rolls Royce, que ayudarian a subir nuestro estatus, y subir los precios apuntando a una audiencia que esté dispuesta a pagar por ellos.


**Paso a paso:**
1. Realiza la agrupación.
2. Renombra las columnas para que sean claras.
3. Interpreta el resultado antes de pasar al siguiente filtro o análisis.

In [20]:
data.groupby('make')['sellingprice'].mean().sort_values(ascending=False)

make
Rolls-Royce    153488.235294
Ferrari        127210.526316
Lamborghini    112625.000000
Bentley         74367.672414
airstream       71000.000000
                   ...
dodge tk          550.000000
Geo               528.947368
dot               500.000000
ford truck        483.333333
Daewoo            400.000000
Name: sellingprice, Length: 96, dtype: float64

In [21]:
data.groupby("make").agg(PrecioPromedio=("sellingprice","mean"),VentasTotales=("make","count")).reset_index().sort_values(by="VentasTotales",ascending=False).head()

         make  PrecioPromedio  VentasTotales
14       Ford    14540.469648          93554
7   Chevrolet    11977.397528          60197
36     Nissan    11739.015960          53946
49     Toyota    12249.321813          39871
10      Dodge    11206.802592          30710

## 6. Análisis de Rentabilidad por Marca

a) Crea una nueva columna `profit` que sea la diferencia entre `mmr` y `sellingprice`.
b) Agrupa por `make` y calcula el beneficio promedio para cada marca.

c) Caso de negocio: Identifica las 5 marcas con mayor beneficio promedio y explica qué acciones estratégicas implementarías (por ejemplo, renegociar precios o invertir en calidad).

Rta: Como se puede observar, las marcas que que se propusieron al inicio no aparecen hasta el top 10 de las que más beneficio promedio tienen, por lo que se podrían ofrecer promociones específicas para estas marcas, para aumentar ventas y la rentabilidad.

In [22]:
data['profit'] = data['mmr']-data["sellingprice"]

In [23]:
data.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate,profit
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),-1000.0
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),-700.0
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST),1900.0
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST),-250.0
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST),-1000.0

In [27]:
data.groupby("make")['profit'].mean().sort_values(ascending=False).head(10)

make
Fisker         2638.888889
Ferrari        2000.000000
Plymouth       1577.500000
Bentley        1560.775862
porsche        1419.736842
kia            1307.142857
Rolls-Royce     805.882353
Tesla           758.695652
Maserati        741.353383
ford tk         675.000000
Name: profit, dtype: float64

## 7. Análisis Temporal: Ventas del Año 2015

a) Filtra el dataset para obtener únicamente las ventas del año 2015 y muestra las primeras 10 filas. Cuantos Vehiculos tiene esta dataset


b) Caso de negocio: Si 2015 muestra comportamientos atípicos en comparación con otros años, ¿deberías ajustar la estrategia basándote en tendencias actuales? Explica tu criterio.

Rta: Si es el caso de que 2015 tenga comportamiento atipicos, entonces deberiamos ajustar la estrategia, y basarnos en las tendencias actuales. Ya que las tendencias actuales son más representativas en el mercado actual y nos ayudarán a tomar mejores decisiones como negocio.

In [32]:
data[data['year'] == 2015].head(10)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate,profit
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),-1000.0
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),-700.0
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST),-250.0
5,2015,Nissan,Altima,2.5 S,Sedan,automatic,1n4al3ap1fn326013,ca,1.0,5554.0,gray,black,enterprise vehicle exchange / tra / rental / t...,15350.0,10900.0,Tue Dec 30 2014 12:00:00 GMT-0800 (PST),4450.0
11,2015,Kia,Optima,LX,Sedan,automatic,5xxgm4a73fg353538,ca,48.0,2034.0,red,tan,kia motors finance,15150.0,17700.0,Tue Dec 16 2014 12:00:00 GMT-0800 (PST),-2550.0
12,2015,Ford,Fusion,SE,Sedan,automatic,3fa6p0hdxfr145753,ca,2.0,5559.0,white,beige,enterprise vehicle exchange / tra / rental / t...,15350.0,12000.0,Tue Jan 13 2015 12:00:00 GMT-0800 (PST),3350.0
13,2015,Kia,Sorento,LX,SUV,automatic,5xyktca66fg561407,ca,5.0,14634.0,silver,black,kia motors america inc,20600.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),-900.0
15,2015,Nissan,Altima,2.5 S,Sedan,automatic,1n4al3ap5fc124223,ca,2.0,11398.0,black,black,enterprise vehicle exchange / tra / rental / t...,14750.0,14100.0,Tue Dec 23 2014 12:00:00 GMT-0800 (PST),650.0
16,2015,Hyundai,Sonata,SE,Sedan,automatic,5npe24af4fh001562,ca,NaN,8311.0,red,—,avis tra,15200.0,4200.0,Tue Dec 16 2014 13:00:00 GMT-0800 (PST),11000.0
20,2015,Chevrolet,Impala,LTZ,Sedan,automatic,2g1165s30f9103921,ca,19.0,14538.0,silver,black,enterprise vehicle exchange / tra / rental / t...,24300.0,7200.0,Tue Jul 07 2015 09:30:00 GMT-0700 (PDT),17100.0

In [35]:
d2=data[data['year'] == 2015]

In [36]:
d2.shape

(9437, 17)

## 8. Comparación por Tipo de Carrocería

a) Agrupa por la columna `body` y calcula el promedio de `sellingprice` para cada tipo.

b) Caso de negocio: Determina qué tipo de carrocería tiene mayor precio promedio y argumenta cómo podrías aprovechar esta información para posicionar una línea premium o ajustar el inventario.

Rta: El tipo de carrocería con mayor precio promedio es el Gran Turismo Convertible, de hecho ocupa las 2 primeras posiciones; para esto podríamos enfocar los esfuerzos de marketing en este tipo de carrocería, destacando sus características premium y su alto valor percibido. Y además establecer precios premium para este tipo de carrocería, justificados por su exclusividad y su alta demanda.

In [38]:
data.groupby('body')['sellingprice'].mean().sort_values(ascending=False)

body
granturismo convertible    79041.666667
GranTurismo Convertible    74000.000000
CTS-V Wagon                50500.000000
cts-v coupe                39707.142857
CTS-V Coupe                38425.750000
                               ...
Xtracab                     5818.750000
xtracab                     5250.000000
Club Cab                    4650.064103
Cab Plus                    2825.000000
Ram Van                     1200.000000
Name: sellingprice, Length: 87, dtype: float64

## 9. Filtros Combinados para un Caso Específico

a) **Paso 1:** Agrupa los datos por `state`, `model` y calcula el promedio de `sellingprice` para ver cuál es el precio promedio por combinación.

b) **Paso 2:** Utiliza el resultado del agrupamiento para filtrar el dataset original. Por ejemplo, filtra los registros de un estado ('ca') y un modelo ('Sorento') cuyo `sellingprice` supere el precio promedio calculado.

c) Caso de negocio: Analiza este segmento y plantea qué acciones implementarías para potenciar las ventas en California, considerando el modelo y el segmento premium.

Rta: Para potenciar las ventas en California podríamos usar publicidad online, creando campañas dirigidas a clientes en California que hayan mostrado interés en vehículos de lujo o en el modelo 'i8'; o también hacer eventos exclusivos para clientes en California, donde puedan conocer el modelo 'i8' y otros vehículos premium.

In [41]:
data.groupby(["state","model"])["sellingprice"].mean().sort_values(ascending=False)

state  model
fl     458 Italia    183000.000000
       i8            162000.000000
       Ghost         160333.333333
       SLS AMG GT    156500.000000
ca     i8            154250.000000
                         ...
mi     G20              200.000000
pr     Sable            150.000000
ca     Paseo            150.000000
hi     Freestar         100.000000
       Montana          100.000000
Name: sellingprice, Length: 16144, dtype: float64

In [51]:
data[(data['state']=="ca")&(data["model"]=="i8")&(data["sellingprice"]>154250)]

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate,profit
146917,2014,BMW,i8,Base,Coupe,automatic,wby2z2c59evx64214,ca,5.0,60.0,white,brown,ferrari of orange county,176000.0,165000.0,Thu Jan 15 2015 04:00:00 GMT-0800 (PST),11000.0
239360,2014,BMW,i8,Base,Coupe,automatic,wby2z2c57evx64633,ca,48.0,124.0,white,black,pacoima motors,172000.0,160000.0,Thu Feb 12 2015 12:30:00 GMT-0800 (PST),12000.0
301118,2014,BMW,i8,Base,Coupe,automatic,wby2z2c50evx64103,ca,5.0,603.0,white,beige,high bid trading co inc,163000.0,158000.0,Thu Feb 12 2015 04:00:00 GMT-0800 (PST),5000.0
363766,2014,BMW,i8,Base,Coupe,automatic,wby2z2c58evx64401,ca,44.0,303.0,white,gray,phelps auto sales,161000.0,161000.0,Thu Feb 26 2015 04:30:00 GMT-0800 (PST),0.0

## 10. Ventas Totales por Estado

a) Agrupa por `state` y calcula la suma de `sellingprice` para cada estado.

b) Caso de negocio: Identifica el estado con mayores ventas totales y discute cómo enfocar campañas de marketing o ampliar la red de distribución en ese estado.

Podríamos considerar la apertura de nuevas tiendas físics en California para aumentar nuestra presencia y accesibilidad; además podríamos asociarnos con distribuidores locales para facilitar el acceso y quizá llegar a más público; y también podríamos crear u optimizar un sitio web, para hacerle más fácil el proceso de compra a los consumidores.

In [53]:
data.groupby('state')['sellingprice'].sum().sort_values(ascending=False)

state
fl                   1.151065e+09
ca                   1.061078e+09
pa                   8.612346e+08
tx                   6.064954e+08
ga                   4.489274e+08
                         ...
3vwd17aj2fm258506    1.330000e+04
3vwd17aj4fm201708    1.320000e+04
3vwd17aj3fm276741    1.320000e+04
3vwd17aj5fm225953    1.320000e+04
3vwd17aj8fm239622    1.320000e+04
Name: sellingprice, Length: 64, dtype: float64

## 11. Rentabilidad por Estado

a) Agrupa por `state` y calcula el promedio de eficiencia operativa. Como no contamos con 'Operating Margin', usa como proxy `profit/sellingprice`.

b) Caso de negocio: Identifica el estado con mayor eficiencia operativa y sugiere estrategias para replicar ese éxito en otros mercados.

Rta: El estado con mejor eficiencia promedio es Nuevo Mexico, y podríamos analizar la logística y la cadena de suministro en Nuevo Mexico, buscando formas de optimizar el transporte, almacenamiento y distribución en otros mercados para reducir costos.

In [55]:
data["efficiency"]=data["profit"]/data["sellingprice"]

In [57]:
data.groupby('state').agg(PromedioEficiencia=("efficiency","mean")).sort_values(by="PromedioEficiencia",ascending=False).head(5)

       PromedioEficiencia
state
nm               1.178797
tx               0.565770
hi               0.429630
ny               0.320112
md               0.292650

## 12. Análisis por Tipo de Transmisión (en lugar de Sales Method)

a) Agrupa el dataset por `transmission` y calcula:
   - La suma de `sellingprice` para cada tipo.
   - El promedio de `sellingprice` para cada tipo.

b) Caso de negocio: ¿Qué tipo de transmisión (automática vs. manual) genera mayores ingresos y qué implicaciones tiene para la estrategia comercial?

Rta: Podríamos segmentar a los clientes en función de sus preferencias por el tipo de transmisión y adaptar nuestras estrategias de marketing y ventas en consecuencia. Por ejemplo, dirigirnos a un público más jóven o deportivo con vehículos de transmisión manual, o también enfocarnos en un público más familiar o que busca comodidad con vehículos de transmisión automática.

In [61]:
data.groupby('transmission')['sellingprice'].sum().sort_values(ascending=False)

transmission
automatic    6.443934e+09
manual       1.966936e+08
sedan        2.047500e+05
Sedan        1.505500e+05
Name: sellingprice, dtype: float64

In [59]:
data.groupby('transmission')['sellingprice'].mean().sort_values(ascending=False)

transmission
Sedan        13686.363636
sedan        13650.000000
automatic    13540.406866
manual       11211.448358
Name: sellingprice, dtype: float64

## 13. Segmentación por Producto Líder

a) Identifica el producto (utiliza la columna `model` como proxy) con mayor cantidad de unidades vendidas. Agrupa por `model` y usa el conteo de registros.

b) Caso de negocio: Si un producto lidera en ventas, ¿cómo ajustarías el inventario y las promociones para maximizar las ganancias?

Rta: Yo ciensto que lo primordial sería asegurarnos de tener suficiente stock del producto "Altima" para satisfacer la demanda, esto evitará perder ventas por falta de disponibilidad. También podríamos considerar la posibilidad de aumentar el stock para este producto en particular priorizando el almacenamiento. Y por último, pordíamos monitorear constantemente el nivel de inventario de este producto, y ajustar los pedidos a los proveedores en función de la demanda; esto nos ayudará a evitar tanto la escasez como el exceso de inventario.

In [63]:
data.groupby('model')['model'].value_counts().sort_values(ascending=False).head(5)

model
Altima    19349
F-150     14479
Fusion    12946
Camry     12545
Escape    11861
Name: count, dtype: int64

## 14. Comparación Crítica entre Retailers

a) Compara dos retailers usando la columna `seller` en cuanto a volumen de ventas y margen de beneficio (usa `profit` como proxy).

b) Caso de negocio: Si un retailer muestra mayores unidades vendidas pero un margen inferior, ¿qué estrategia recomendarías (por ejemplo, optimización de costos, cambio en política de descuentos, etc.)? Justifica tu propuesta.

Rta: Podríamos enfocarnos en vender productos con mayor margen de beneficio, en lugar de productos de bajo margen, aprovechando la imágen que le hemos dado a la marca. Luego mejorar la experiencia del cliente, ofreciendo una mejor experiencia al cliente, lo que puede aumentar la fidelidad y la disposición a pagar precios más altos, lo que a su vez mejora el margen de beneficio.


**Paso a paso:**
1. Agrupa por `seller` y calcula la suma de `sellingprice` y el promedio de `profit`.
2. Ordena los resultados para identificar los líderes en volumen y analiza el margen.
3. Propón una estrategia basada en los resultados.

In [65]:
data.groupby('seller').agg(VentasTotales=("sellingprice","sum"),BeneficioPromedio=("profit","mean")).sort_values(by="VentasTotales",ascending=False).head(5)

                               VentasTotales  BeneficioPromedio
seller
ford motor credit company llc    340960125.0         216.393122
nissan-infiniti lt               272104560.0         -70.225969
the hertz corporation            250863168.0         189.344063
nissan infiniti lt               216158321.0          92.654989
avis corporation                 203432330.0         -20.590510

## 15. Caso Integrador: Estrategia Comercial Global

a) **Paso 1:** Identifica cada criterio basado en los análisis anteriores:
   - **Retailer con mayores ventas totales:** Usa la columna `seller` del resumen de retailers.
   - **Estado con mayores ventas totales:** Del agrupamiento por `state`.
   - **Producto con mayor unidades vendidas:** Usa la columna `model`.
   - **Tipo de transmisión con mayores ventas totales:** Agrupa por `transmission`.

b) **Paso 2:** Filtra el dataset original usando cada uno de estos criterios, uno a uno, y luego combínalos en un filtro final.

c) Con base en el análisis combinado, redacta un breve informe (3-4 líneas) proponiendo una estrategia comercial integral para maximizar la rentabilidad, considerando inversión en canales, promociones específicas y optimización de inventario.

Rta: Para maximizar la rentabilidad, yo propondría enfocar la estrategia comercial en Ford Motor Credit Company llc, con especial atención al estado de Florida. Obviamente sin olvidar la inversión en canales de marketing digital y publicidad localizada en este estado, promocionando el F-150 con transmisión automática. Además, podríamos optimizar el inventario para asegurarnos de tener la disponibilidad de este producto en Florida.

d) Caso de negocio: Utiliza la integración de estos criterios para definir en qué segmento enfocar la estrategia global.

Rta: Nuestro segmento específico serán las personas que vivan en Florida, que busquen comprar el F-150 con transmisión automática (Aunque no sé si exista) y que vivan cerca o lo busquen a través de Ford Motor Credit Company llc.
En otras palabras, personas con el suficiente poder adquisitivo para comprar un F150, que vivan en Florida y prefieran la cómodidad de manejar un automático.

In [67]:
data.groupby("seller").agg(ventasTotales=("sellingprice","sum")).sort_values(by="ventasTotales",ascending=False).head(5)

                               ventasTotales
seller
ford motor credit company llc    340960125.0
nissan-infiniti lt               272104560.0
the hertz corporation            250863168.0
nissan infiniti lt               216158321.0
avis corporation                 203432330.0

In [68]:
data.groupby("state").agg(ventasTotales=("sellingprice","sum")).sort_values(by="ventasTotales",ascending=False).head(5)

       ventasTotales
state
fl      1.151065e+09
ca      1.061078e+09
pa      8.612346e+08
tx      6.064954e+08
ga      4.489274e+08

In [69]:
data.groupby("model").agg(ventasTotales=("sellingprice","sum")).sort_values(by="ventasTotales",ascending=False).head(5)

         ventasTotales
model
F-150      272669759.0
Altima     220986008.0
Escape     165884802.0
Fusion     159912520.0
G Sedan    147918806.0

In [70]:
data.groupby("transmission").agg(ventasTotales=("sellingprice","sum")).sort_values(by="ventasTotales",ascending=False).head(5)

              ventasTotales
transmission
automatic      6.443934e+09
manual         1.966936e+08
sedan          2.047500e+05
Sedan          1.505500e+05